apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nodejs-webapp
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: simple-nodejs-webapp
  template:
    metadata:
      labels:
        app: simple-nodejs-webapp
    spec:
      containers:
      - name: simple-nodejs-webapp
        image: florianamiot/simple-nodejs-webapp:version1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

      
 